
services:
  db:
    image: postgres:15
    container_name: codenames_postgres
    environment:
      POSTGRES_DB: codenamesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - codenames_net

  backend:
    build: .
    container_name: codenames_backend
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: codenamesdb
    ports:
      - "3000:3000"
    networks:
      - codenames_net

networks:
  codenames_net:
